### ISSUE TITLE
Upgrade API/impl

### ISSUE THREAD

**Issue by JohnKhandygo** [SergeyChernonog/ProgTechJava2018#3]
- [x] В классе Address некорректно реализован метод `hashCode`.
- [x] Метод  https://github.com/SergeyChernonog/ProgTechJava2018/blob/be477f6eade4abf2c8e554757ff797315b4f2c62/src/AddressBook/AddressBook.java#L14 "выставляет наружу" детали реализации `AddressBook`. Это позволяет модифицировать внутреннее состоянее экземпляра `AdressBook`, минуя специфические проверки, реализованные в самом классе. 
- [x] Метод https://github.com/SergeyChernonog/ProgTechJava2018/blob/be477f6eade4abf2c8e554757ff797315b4f2c62/src/AddressBook/AddressBook.java#L18 не обрабатывает случай дубликации записей (для перезаписи существует метод `rewrite`).
- [x] Метод https://github.com/SergeyChernonog/ProgTechJava2018/blob/be477f6eade4abf2c8e554757ff797315b4f2c62/src/AddressBook/AddressBook.java#L22 может вернуть `null`, что не очень удобно для сторонних пользователей. В общем считается, что не стоит использовать `null` как значение, обозначающее отсутствие чего-либо. Вместо этого лучше использовать `Optional` или завести специальное значение `Address`, обозначающее отсутствующий адресс, но с которым можно работать так же, как и с любым другим значением `Address` (см. [null object pattern](https://en.wikipedia.org/wiki/Null_object_pattern)).
- [x] По методу https://github.com/SergeyChernonog/ProgTechJava2018/blob/be477f6eade4abf2c8e554757ff797315b4f2c62/src/AddressBook/AddressBook.java#L26 невозможно понять, была ли удалена запись на самом деле, или ее изначально не существовало в `AdressBook` (иногда это полезно). Для решения этой проблемы можно либо возвращать `boolean`, либо объект, который был удален (так реализован метод `remove` в `Map`).
- [x] Реализации методов https://github.com/SergeyChernonog/ProgTechJava2018/blob/be477f6eade4abf2c8e554757ff797315b4f2c62/src/AddressBook/AddressBook.java#L33 и https://github.com/SergeyChernonog/ProgTechJava2018/blob/be477f6eade4abf2c8e554757ff797315b4f2c62/src/AddressBook/AddressBook.java#L43 почти идентичны.

**Comment by JohnKhandygo** [comment]
Все предыдущие замечания исправлены, замечательно. 

- [ ] Вы никак не регламентируете поведение своих классов и методов в случае, когда некоторые их аргументы (например, `adress`) являются `null`. Все эти случаи также стоит отразить в тестах и javadoc.

**Comment by SergeyChernonog** [comment]
Изменил методы add и getAddress

**Comment by JohnKhandygo** [comment]
- А как насчет `rewrite`? А что, если `name = null`?
- Теперь непонятно, как интерпретировать возврат `NullAddress` из `getAddress`. Это значит, что такой записи нет или это значит, что такая запись есть, но у нее реально записан `NullAddress` (который Вы можете добавить в `add`)?

**Comment by SergeyChernonog** [comment]
Изменил методы add и rewrite

**Comment by SergeyChernonog** [comment]
Тесты с name == null проходят, я не очень понимаю, что именно тут надо исправить

**Comment by JohnKhandygo** [comment]
То есть Вы считаете, что это нормально? Вот такой тест, например, проходит
'''
final AddressBook book = new AddressBook();
final RealAddress addr = new RealAddress("street", 1, 2);
book.add(null, addr);
assertEquals(addr, book.getAddress(null));
'''

**Comment by SergeyChernonog** [comment]
Добавил обработку null в add

**Comment by JohnKhandygo** [comment]
Теперь тест типа такого
```
final AddressBook book = new AddressBook();
book.add(null, new RealAddress("street", 1, 2));
final RealAddress otherAddr = new RealAddress("otherStreet", 4, 5);
final boolean addResult = book.add("", otherAddr);
assertEquals(otherAddr, book.getAddress(""));
//assertTrue(addResult);
```
не будет проходить, потому что Вы уже добавили `name = ""` в `Map`. Поймите, помимо бизнес логики Вашего приложения и непосредственно кода существует еще такое понятие, как **семантика**, то есть его значение, смысл. Если говорить очень грубо, то в ООП семантика происходит из сопоставления классов (в смысле ООП) и реальных объектов. То есть смысл класса `Car`, например заключается в том, что он моделирует реальный объект "машина" и все его методы работают исходя из этого принципа. Еще раз --- это очень грубый подход, однако в данном случае Вы можете обратиться к нему.

**Comment by JohnKhandygo** [comment]
Плюс к тому, у Вас сейчас не все тесты проходят.
