### ISSUE TITLE
Upgrade tests

### ISSUE THREAD

**Issue by JohnKhandygo** [SergeyChernonog/ProgTechJava2018#5]
Тесты не покрывают некоторые случаи использования AdressBook (например, работа с полностью пустым AdressBook). При этом тест https://github.com/SergeyChernonog/ProgTechJava2018/blob/be477f6eade4abf2c8e554757ff797315b4f2c62/test/AddressBook/AddressBookTest.java#L24 по факту не тестирует ничего: Вы просто проверяете, что одинаковая модификация над одинаковыми объектами дают одинаковые объекты. Суть операции добавления в том, что добавленый объект затем может быть извлечен, и именно это надо проверить. Подобная шутка встречается в тестах достаточно часто.

**Comment by JohnKhandygo** [comment]
У Вас немножко бардак в тестах. Попробуйте более точно придерживаться концепции [given - when - than](https://martinfowler.com/bliki/GivenWhenThen.html) и помните, что каждый тест в идеале должен проверять что-то "одно". Более конкретно: 
- [ ] Зачастую не понятно, зачем Вам понадобилась лишняя адрессная книга (например, в `getAddress`) или неизвестный адресс `otherName` (например, в `add`). 
- [ ] Вместо того, чтобы сравнивать экземпляр `AdressBook` с пустой адресной книгой лучше вынести в `AdressBook` небольшой метод `isEmpty`. Альтернативный подход заключается в том, чтобы использовать внутреннее представление `AdressBook` напрямую (его, конечно, нельзя выставлять наружу, но никто не запрещал сделать его package private для тестов).
- [ ] Вместо `assertTrue(!x)` лучше писать `assertFalse(x)`.
- [ ] Раз уж Вы сделали тест на `RealAddress`, сделайте также тест и на `NullAddress`.

**Comment by JohnKhandygo** [comment]
Честно говоря, тесты не стали выглядеть сильно лучше. Попробуйте сделать их более атомарными, то есть такими, чтобы каждый тестовый метод покрывал один конкретный вариант использования.

**Comment by SergeyChernonog** [comment]
Добавил новые тесты

**Comment by JohnKhandygo** [comment]
И что? Я просил отрефакторить Ваши тесты, сделать их более атомарными. Сейчас у Вас в каждом тестовом методе (методе, помеченном `@Test`) адское нагромождение кода. Вы пытаетесь в одном месте протестировать все аспекты работы методов `AddressBook` сразу. По факту тесты --- это такой же артефакт, как и код. Тесты, помимо того, что позволяют Вам отлавливать ошибки на этапе модификации, также играют роль своего рода документации (просто она выражена в форме примеров). Поэтому код тестов должен поддерживаться в хорошем состоянии наравне с основным кодом приложения.

**Comment by JohnKhandygo** [comment]
Плюс к тому, у Вас сейчас не все тесты проходят.

**Comment by JohnKhandygo** [comment]
- [ ] У Вас все еще не все тесты проходят. 
- [ ] У Вас каждый тест в `AddressBookTest` начинается с инстанцирования нового экземпляра `AddressBook`. Для устранения повторений используйте junit5 аннотацию [BeforeEach](https://junit.org/junit5/docs/current/user-guide/#writing-tests-annotations).

**Comment by SergeyChernonog** [comment]
А какие именно тесты не проходят?

**Comment by SergeyChernonog** [comment]
![scrn](https://user-images.githubusercontent.com/31696547/37876897-0103d758-305c-11e8-881d-7bc351e93e8b.jpg)

**Comment by SergeyChernonog** [comment]
Чего я не понял ?

**Comment by JohnKhandygo** [comment]
А это единственный класс с текстами, который есть, да?

**Comment by SergeyChernonog** [comment]
Нашел ошибку
